# Alpha Agent Pool Configuration
pool_id: "alpha_pool_production"
environment: "production"
enable_enhanced_lifecycle: true
worker_threads: 8

# Retry policy configuration
retry:
  max_attempts: 5
  base_delay: 1.0
  max_delay: 120.0
  backoff_multiplier: 2.0
  jitter: true

# Circuit breaker configuration  
circuit_breaker:
  failure_threshold: 10
  recovery_timeout: 300.0

# Backpressure configuration
backpressure:
  max_queue_size: 1000
  warning_threshold: 0.8
  rate_limit_rps: 50.0

# Observability configuration
observability:
  enable_metrics: true
  enable_tracing: true
  enable_detailed_logging: false
  metrics_port: 9090
  log_level: "INFO"

# Strategy execution configuration
strategy:
  default_timeout: 60.0
  warmup_enabled: true
  max_concurrent_strategies: 20

# Feature retrieval configuration
feature:
  cache_ttl_seconds: 600
  max_cache_size: 5000
  fetch_timeout: 30.0

# A2A memory coordination configuration
memory:
  memory_url: "http://127.0.0.1:8010"
  connection_timeout: 15.0
  retry_attempts: 3

# MCP server/client configuration
mcp:
  server_host: "0.0.0.0"
  server_port: 8081
  client_timeout: 45.0
  transport: "sse"
