# CoinGecko API configuration

agent_id: coingecko_agent
api:
  base_url: "https://api.coingecko.com/api/v3"
  endpoints:
    market_chart: "/coins/{coin_id}/market_chart"
    coin_info: "/coins/{coin_id}"
    markets: "/coins/markets"
    global_stats: "/global"
    trending: "/search/trending"
    exchanges: "/exchanges"
  default_currency: "usd"
  default_days: 30
authentication:
  api_key: ""  # Optional - CoinGecko has a free tier without API key
  secret_key: ""  # Not used by CoinGecko
constraints:
  timeout: 30
  rate_limit_per_minute: 30  # Free tier: 30 calls/minute, Pro: 500 calls/minute
  max_days_history: 365  # Maximum days of historical data in single request
  supported_currencies: 
    - "usd"
    - "eur" 
    - "jpy"
    - "btc"
    - "eth"
    - "gbp"
    - "aud"
    - "cad"
    - "chf"
    - "cny"
    - "krw"
llm_enabled: false
features:
  include_market_cap: true
  include_volume: true
  include_price_changes: true
  include_supply_data: true
  cache_duration_hours: 1  # Cache data for 1 hour (crypto data changes frequently)
  enable_derived_metrics: true  # Calculate additional metrics like moving averages, volatility