environment: production

# Database Configuration
database:
  uri: "bolt://localhost:7687"
  username: "neo4j"
  password: "finagent123"
  database: "finagent"
  max_connection_pool_size: 100
  connection_timeout: 30
  max_retry_time: 30
  encrypted: true
  trust: "TRUST_SYSTEM_CA_SIGNED_CERTIFICATES"
  enable_intelligent_indexing: true
  memory_cache_size: 5000
  semantic_search_enabled: true

# Server Configuration
server:
  host: "0.0.0.0"
  port: 8000
  debug: false
  log_level: "WARNING"
  cors_enabled: true
  cors_origins: []  # Restrict CORS in production
  workers: 4
  max_connections: 5000
  keepalive_timeout: 10
  api_key_required: true
  api_key: "your-production-api-key-here"

# Memory Configuration
memory:
  graph_memory_enabled: true
  vector_memory_enabled: true
  cache_enabled: true
  max_nodes: 100000
  max_relationships: 500000
  auto_cleanup_enabled: true
  cleanup_interval_hours: 12
  vector_dimension: 384
  similarity_threshold: 0.7
  max_vectors: 100000
  indexing_enabled: true
  auto_index_creation: true
  index_update_interval: 600

# MCP Configuration
mcp:
  transport_type: "stdio"
  protocol_version: "2024-11-05"
  enable_all_tools: true
  enabled_tools: []
  tool_timeout: 60
  max_concurrent_operations: 50
  operation_timeout: 120

# A2A Configuration
a2a:
  websocket_enabled: true
  real_time_enabled: true
  max_message_history: 10000
  message_retention_hours: 48
  broadcast_enabled: true
  max_concurrent_agents: 1000
  agent_timeout_minutes: 60
  heartbeat_interval: 60

# Logging Configuration
logging:
  level: "WARNING"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_enabled: true
  file_path: "logs/finagent_prod.log"
  max_file_size: "50MB"
  backup_count: 10
  database_log_level: "ERROR"
  server_log_level: "WARNING"
  memory_log_level: "WARNING"

# Global Settings
project_name: "FinAgent"
version: "2.0.0"
api_prefix: "/api/v1"

# Port Configuration for Different Servers
ports:
  memory_server: 8000
  mcp_server: 8001
  a2a_server: 8002
  
# Database Initialization Settings
database_init:
  auto_create_indexes: true
  auto_create_constraints: true
  clear_on_startup: false
  seed_data_enabled: false
  backup_before_init: true
  
  # Required indexes
  required_indexes:
    - name: "memory_search_index"
      type: "fulltext"
      labels: ["Memory"]
      properties: ["summary", "keywords"]
    - name: "memory_event_type_index"
      type: "btree"
      labels: ["Memory"]
      properties: ["event_type"]
    - name: "memory_agent_id_index"
      type: "btree"
      labels: ["Memory"]
      properties: ["agent_id"]
    - name: "memory_timestamp_index"
      type: "btree"
      labels: ["Memory"]
      properties: ["timestamp"]
    - name: "memory_session_id_index"
      type: "btree"
      labels: ["Memory"]
      properties: ["session_id"]
      
  # Required constraints
  required_constraints:
    - name: "memory_id_unique"
      type: "uniqueness"
      labels: ["Memory"]
      properties: ["memory_id"]
