"""Postgres-backed BacktestDatabase implementation (run history, the "cold half").

Selected instead of the default SQLite BacktestDatabase when AGENT_RUNS_DATABASE_URL is
set (see database.py's _build_backtest_db). Exists because the SQLite store lives
in DATABASE_PATH, which resets to the committed seed database on every deploy of
the disk-less Render free-tier host -- silently deleting every backtest run,
equity curve, trade log and decision log, which is why issue #145 (the leaderboard
refresh cron) is blocked. Method surface, return schemas and behavior are
identical to BacktestDatabase; only the SQL dialect differs, plus two named
timestamp divergences on upsert (see insert_run) and a batched get_equity_curves.

The hot half stays local: get_idempotency/put_idempotency are delegated to an
embedded plain BacktestDatabase so the per-step agent request never gains a
network round-trip. protocol_runs/protocol_steps are not ours -- they belong to
domain/runs/repository.py and are untouched.
"""
from __future__ import annotations

import json
from typing import Any, Dict, List, Optional

from dashboard.backend.database import BacktestDatabase
from dashboard.backend.db_url import require_postgres_url


class PostgresBacktestDatabase:
    def __init__(self, database_url: str):
        self.database_url = require_postgres_url(database_url)
        self._sqlite = BacktestDatabase()   # hot half: idempotency_keys stays local
        self._init_schema()

    def _get_connection(self):
        # Pooled checkout: same context-manager transaction semantics as
        # psycopg.connect (commit on clean exit), returned to the pool on close.
        from dashboard.backend.db_pool import get_pool

        return get_pool(self.database_url).connection()

    def _init_schema(self) -> None:
        # created_at/updated_at are TEXT with a Postgres DEFAULT that produces
        # SQLite's exact CURRENT_TIMESTAMP string ("YYYY-MM-DD HH:MM:SS", UTC),
        # so read shapes are identical across both stores and the *database*
        # stamps the row exactly like SQLite does -- not clock-dependent app code.
        created_at_default = (
            "DEFAULT to_char(now() AT TIME ZONE 'utc', 'YYYY-MM-DD HH24:MI:SS')"
        )

        with self._get_connection() as conn:
            with conn.cursor() as cur:
                # --------------------------------------------------------
                # CREATE: full post-migration column set for all five
                # "cold" tables (agent_runs, equity_timeseries, trades,
                # backtest_decisions, run_manifest). Mirrors database.py
                # after every lazy migration has run, post Task 2's
                # actions_trace_ref addition.
                # --------------------------------------------------------
                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS agent_runs (
                        run_id TEXT PRIMARY KEY,
                        session_id TEXT NOT NULL,
                        agent_name TEXT NOT NULL,
                        mode TEXT NOT NULL,
                        start_date TEXT NOT NULL,
                        end_date TEXT NOT NULL,
                        initial_equity DOUBLE PRECISION NOT NULL,
                        final_equity DOUBLE PRECISION,
                        total_return DOUBLE PRECISION,
                        sharpe_ratio DOUBLE PRECISION,
                        max_drawdown DOUBLE PRECISION,
                        num_trades INTEGER DEFAULT 0,
                        llm_model TEXT DEFAULT 'rule-based',
                        llm_calls INTEGER DEFAULT 0,
                        input_tokens INTEGER DEFAULT 0,
                        output_tokens INTEGER DEFAULT 0,
                        est_cost_usd DOUBLE PRECISION DEFAULT 0,
                        metadata TEXT,
                        created_at TEXT NOT NULL {created_at_default},
                        updated_at TEXT NOT NULL {created_at_default},
                        baseline_djia_run_id TEXT,
                        baseline_buyhold_run_id TEXT
                    )
                    """
                )

                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS equity_timeseries (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        run_id TEXT NOT NULL
                            REFERENCES agent_runs(run_id) ON DELETE CASCADE,
                        timestamp TEXT NOT NULL,
                        equity DOUBLE PRECISION NOT NULL,
                        cash DOUBLE PRECISION NOT NULL,
                        positions_value DOUBLE PRECISION NOT NULL,
                        daily_return DOUBLE PRECISION,
                        native_equity DOUBLE PRECISION,
                        native_cash DOUBLE PRECISION,
                        native_positions_value DOUBLE PRECISION,
                        fx_rate DOUBLE PRECISION,
                        created_at TEXT NOT NULL {created_at_default},
                        UNIQUE (run_id, timestamp)
                    )
                    """
                )

                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS trades (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        run_id TEXT NOT NULL
                            REFERENCES agent_runs(run_id) ON DELETE CASCADE,
                        timestamp TEXT NOT NULL,
                        symbol TEXT NOT NULL,
                        quantity INTEGER NOT NULL,
                        side TEXT NOT NULL,
                        price DOUBLE PRECISION NOT NULL,
                        value DOUBLE PRECISION NOT NULL,
                        reason TEXT,
                        native_price DOUBLE PRECISION,
                        native_value DOUBLE PRECISION,
                        fx_rate DOUBLE PRECISION,
                        created_at TEXT NOT NULL {created_at_default}
                    )
                    """
                )

                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS backtest_decisions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        run_id TEXT NOT NULL
                            REFERENCES agent_runs(run_id) ON DELETE CASCADE,
                        step_index INTEGER NOT NULL,
                        timestamp TEXT NOT NULL,
                        decision_source TEXT NOT NULL,
                        actions_submitted TEXT,
                        actions_executed INTEGER DEFAULT 0,
                        context_ref TEXT,
                        actions_trace_ref TEXT,
                        created_at TEXT NOT NULL {created_at_default}
                    )
                    """
                )

                # No FK: deliberate. The SQLite side has none either, and its
                # rows are deleted explicitly (see delete_run/clear_all).
                cur.execute(
                    f"""
                    CREATE TABLE IF NOT EXISTS run_manifest (
                        run_id TEXT PRIMARY KEY,
                        manifest_json TEXT NOT NULL,
                        created_at TEXT NOT NULL {created_at_default}
                    )
                    """
                )

                cur.execute(
                    "CREATE INDEX IF NOT EXISTS idx_agent_runs_session "
                    "ON agent_runs(session_id)"
                )
                cur.execute(
                    "CREATE INDEX IF NOT EXISTS idx_agent_runs_session_mode "
                    "ON agent_runs(session_id, mode)"
                )
                cur.execute(
                    "CREATE INDEX IF NOT EXISTS idx_run_timestamp "
                    "ON equity_timeseries(run_id, timestamp)"
                )
                cur.execute(
                    "CREATE INDEX IF NOT EXISTS idx_trades_run "
                    "ON trades(run_id, timestamp)"
                )
                cur.execute(
                    "CREATE INDEX IF NOT EXISTS idx_decisions_run "
                    "ON backtest_decisions(run_id, step_index)"
                )

                # ADDING A COLUMN LATER? It must go in an `ALTER TABLE ... ADD COLUMN IF
                # NOT EXISTS` below, *not* only in the CREATE above. CREATE TABLE IF NOT
                # EXISTS silently no-ops once the table exists, so an existing deployment
                # would never gain the column, and every query naming it would raise
                # UndefinedColumn -- 500ing this whole surface while /health stays green.
                # See domain/agents/repository_postgres.py for the full worked example.
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "session_id TEXT DEFAULT 'legacy-demo-session'"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "llm_model TEXT DEFAULT 'rule-based'"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "baseline_djia_run_id TEXT"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "baseline_buyhold_run_id TEXT"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "llm_calls INTEGER DEFAULT 0"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "input_tokens INTEGER DEFAULT 0"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "output_tokens INTEGER DEFAULT 0"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS "
                    "est_cost_usd DOUBLE PRECISION DEFAULT 0"
                )
                cur.execute(
                    "ALTER TABLE agent_runs ADD COLUMN IF NOT EXISTS metadata TEXT"
                )

                cur.execute(
                    "ALTER TABLE backtest_decisions ADD COLUMN IF NOT EXISTS "
                    "context_ref TEXT"
                )
                cur.execute(
                    "ALTER TABLE backtest_decisions ADD COLUMN IF NOT EXISTS "
                    "actions_trace_ref TEXT"
                )

                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS quantity INTEGER"
                )
                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS side TEXT"
                )
                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS "
                    "value DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS reason TEXT"
                )

                cur.execute(
                    "ALTER TABLE equity_timeseries ADD COLUMN IF NOT EXISTS "
                    "native_equity DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE equity_timeseries ADD COLUMN IF NOT EXISTS "
                    "native_cash DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE equity_timeseries ADD COLUMN IF NOT EXISTS "
                    "native_positions_value DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE equity_timeseries ADD COLUMN IF NOT EXISTS "
                    "fx_rate DOUBLE PRECISION"
                )

                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS "
                    "native_price DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS "
                    "native_value DOUBLE PRECISION"
                )
                cur.execute(
                    "ALTER TABLE trades ADD COLUMN IF NOT EXISTS "
                    "fx_rate DOUBLE PRECISION"
                )

                # Postgres counterpart of SQLite's
                # _ensure_equity_timeseries_uniqueness/_apply_equity_timeseries_uniqueness:
                # the natural key that makes a rerun replace rather than duplicate, and
                # what ON CONFLICT (run_id, timestamp) needs to exist at all (Task 4/5).
                #
                # NOTHING STATIC GUARDS THIS LINE. The lazy-migration guard
                # (test_postgres_twin_repeats_every_sqlite_lazy_migration) regex-matches
                # only `ALTER TABLE ... ADD COLUMN` strings, and the SQLite original
                # protects this key with a unique *index*, not a column -- so its
                # omission here would be invisible to every static check. Only a live
                # Postgres upsert test (Task 9, @pg_only) would catch a missing/dropped
                # copy of this statement.
                cur.execute(
                    "CREATE UNIQUE INDEX IF NOT EXISTS "
                    "uq_equity_timeseries_run_timestamp "
                    "ON equity_timeseries (run_id, timestamp)"
                )

    def get_idempotency(self, run_id: str, step_index: int, idem_key: str) -> Optional[Dict[str, Any]]:
        return self._sqlite.get_idempotency(run_id, step_index, idem_key)

    def put_idempotency(self, run_id: str, step_index: int, idem_key: str, ack: Dict[str, Any]) -> None:
        self._sqlite.put_idempotency(run_id, step_index, idem_key, ack)
